"""Publication-quality posterior plots using ArviZ.

Loads MCMC chain files (.npz or .nc) generated by run_pymc.py or
run_hierarchy_pymc.py and produces:

  trace       Posterior trace + density per parameter
  posterior   Marginal posterior distributions with HDI
  forest      Side-by-side parameter comparison (within or between models)
  pair        Pairwise joint posteriors with KDE
  rank        Rank plots for convergence diagnostics
  ess         Effective sample size evolution
  autocorr    Autocorrelation by chain

When two models are provided (e.g. NH and IH), forest and pair plots
are overlaid for direct comparison.

Usage:
    PYTHONPATH=../build/pybind:.. .venv/bin/python plot_arviz.py pymc_fit.nc
    PYTHONPATH=../build/pybind:.. .venv/bin/python plot_arviz.py hmc_chains_nh.npz
    PYTHONPATH=../build/pybind:.. .venv/bin/python plot_arviz.py --nh hmc_chains_nh.npz --ih hmc_chains_ih.npz

Environment:
    JAX_BARGER_FLOAT32=1   (only needed if loading .npz with physics data)
"""

import sys, os, argparse, numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

PNAMES = ['DM2', 'Dm2', 'th23', 'th13', 'dcp', 'th12']


def load_chains(filepath):
    """Load chains from .npz or .nc, returning arviz DataTree."""
    import arviz as az
    ext = os.path.splitext(filepath)[1].lower()
    if ext == '.npz':
        d = np.load(filepath, allow_pickle=True)
        chains = d['chains']  # (n_chains, n_samples, 6)
        posterior = {n: chains[:, :, i] for i, n in enumerate(PNAMES)}
        return az.from_dict({'posterior': posterior}, sample_dims=['chain', 'draw'])
    elif ext == '.nc':
        return az.from_netcdf(filepath)
    else:
        raise ValueError(f'Unknown file format: {ext}')


def make_plots(idata, label, outdir, backend='matplotlib'):
    """Generate standard diagnostic plots for a single model."""
    import arviz_plots as azp
    azp.style.use('arviz-variat')

    os.makedirs(outdir, exist_ok=True)
    suffix = f'_{label}'

    plots = [
        ('trace',       azp.plot_trace,       dict(var_names=PNAMES, group='posterior')),
        ('posterior',   azp.plot_dist,        dict(var_names=PNAMES, group='posterior')),
        ('pair',        azp.plot_pair,        dict(var_names=PNAMES, group='posterior')),
        ('rank',        azp.plot_rank,        dict(var_names=PNAMES, group='posterior')),
    ]

    for name, func, kwargs in plots:
        print(f'  {label} {name}...')
        pc = func(idata, backend=backend, **kwargs)
        path = os.path.join(outdir, f'{name}{suffix}.png')
        pc.savefig(path)
        print(f'    -> {path}')


def compare_plots(idata_nh, idata_ih, outdir, backend='matplotlib'):
    """Generate comparison plots between two models."""
    import arviz_plots as azp

    os.makedirs(outdir, exist_ok=True)

    models = {'NH': idata_nh, 'IH': idata_ih}

    # Forest plot — joint parameter comparison
    print('  compare forest...')
    pc = azp.plot_forest(
        models, var_names=PNAMES, group='posterior',
        combined=True, backend=backend,
    )
    path = os.path.join(outdir, 'forest_nh_vs_ih.png')
    pc.savefig(path)
    print(f'    -> {path}')

    # Ridge plot — stacked posteriors per parameter
    print('  compare ridge...')
    try:
        pc = azp.plot_ridge(
            models, var_names=PNAMES, group='posterior',
            backend=backend,
        )
        path = os.path.join(outdir, 'ridge_nh_vs_ih.png')
        pc.savefig(path)
        print(f'    -> {path}')
    except Exception as e:
        print(f'    SKIPPED: {e}')


# ═══════════════════════════════════════════════════════════════════════════════
# CLI
# ═══════════════════════════════════════════════════════════════════════════════

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='ArviZ posterior plotting')
    parser.add_argument('file', nargs='?', help='Single model chain file (.npz or .nc)')
    parser.add_argument('--nh', help='NH chain file for comparison')
    parser.add_argument('--ih', help='IH chain file for comparison')
    parser.add_argument('--outdir', default='plots', help='Output directory (default: plots/)')
    parser.add_argument('--backend', default='matplotlib',
                        choices=['matplotlib', 'plotly', 'bokeh'])
    args = parser.parse_args()

    from arviz_plots import style
    style.use('arviz-variat')

    if args.nh and args.ih:
        print(f'Loading NH: {args.nh}')
        nh = load_chains(args.nh)
        print(f'Loading IH: {args.ih}')
        ih = load_chains(args.ih)
        print(f'Making comparison plots -> {args.outdir}/')
        compare_plots(nh, ih, args.outdir, args.backend)
        print(f'Making NH-only plots -> {args.outdir}/')
        make_plots(nh, 'nh', args.outdir, args.backend)
        print(f'Making IH-only plots -> {args.outdir}/')
        make_plots(ih, 'ih', args.outdir, args.backend)
    elif args.file:
        print(f'Loading: {args.file}')
        idata = load_chains(args.file)
        label = os.path.splitext(os.path.basename(args.file))[0]
        print(f'Making plots -> {args.outdir}/')
        make_plots(idata, label, args.outdir, args.backend)
    else:
        parser.print_help()
        sys.exit(1)

    print('Done.')
